default: &default
  adapter: postgresql
  pool: 5
  username: ubuntu
  password: 123456

development:
  <<: *default
  database: coderwall_development

test:
  <<: *default
  database: knowscode_test

production:
  <<: *default
  database: knowscode_production
